apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-k3s-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-testapp
  template:
    metadata:
      labels:
        app: php-testapp
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: php-testapp
        image: sandesh2000/k3s-php-jenkins:19
        imagePullPolicy: "Always"
---
apiVersion: v1
kind: Service
metadata:
  name: php-k3s-service
spec:
  type: NodePort
  selector:
    app: php-testapp
  ports:
  - nodePort: 32169
    port: 8081
    targetPort: 80